Section A - Exception handling

In [2]:
# 1. safe_divide(a, b)

In [70]:
def safe_divide(a, b):
    try:
        result = a / b
        print("Result:", result)
        
    except ZeroDivisionError:
        print("Error: Cannot divide by zero")
        
    except TypeError:
          print("Error: Invalid data type")

    finally:
          print("Operation attempted")

safe_divide(10, 2)
safe_divide(10, 0)
safe_divide(10, "A")

Result: 5.0
Operation attempted
Error: Cannot divide by zero
Operation attempted
Error: Invalid data type
Operation attempted


In [71]:
# 2. validate_age(age)

In [72]:
class InvalidAgeError(Exception):
    pass

def validate_age(age):
    if age < 0 or age > 120:
        raise InvalidAgeError("Invalid age")
    print("Valid age:", age)

ages = [25, -5, 130]

for age in ages:
    try:
        validate_age(age)
    except InvalidAgeError as e:
        print(e)

Valid age: 25
Invalid age
Invalid age


In [73]:
# 3. User input validation

In [74]:
user_inputs = ['10', 'abc', '0', '5']

for i in user_inputs:
    try:
        result = 100/int(i)
        print("Result:",result)

    except ValueError:
        print("Value error:",i)

    except ZeroDivisionError:
        print("Zero division error")

    except Exception:
        print("Some other error")

Result: 10.0
Value error: abc
Zero division error
Result: 20.0


Section B - NumPy

In [75]:
# 4. Array 1 to 20

In [76]:
import numpy as np

arr = np.arange(1, 21)

a = arr.reshape(4, 5)
print(a)

print("Row sum :",a.sum(axis = 1))
print("Column sum:",a.sum(axis = 0))

print("Greater than 10 =",arr[arr > 10])

arr[arr % 2 == 0] = -1
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Row sum : [15 40 65 90]
Column sum: [34 38 42 46 50]
Greater than 10 = [11 12 13 14 15 16 17 18 19 20]
[ 1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]


In [77]:
# 5. Matrix operation

In [78]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

B = np.array([[5, 6], [7, 8]])

print("Addition:")
print(A + B)

print("Subtraction:")
print(A - B)

print("Multiplication:")
print(A * B)

print("Matrix multiplication:")
print(A @ B)

print("Transpose:")
print(A.T)

print("Determinant:")
print(np.linalg.det(A))

print("Inverse:")
print(np.linalg.inv(A))

Addition:
[[ 6  8]
 [10 12]]
Subtraction:
[[-4 -4]
 [-4 -4]]
Multiplication:
[[ 5 12]
 [21 32]]
Matrix multiplication:
[[19 22]
 [43 50]]
Transpose:
[[1 3]
 [2 4]]
Determinant:
-2.0000000000000004
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [79]:
# 6. Random array

In [80]:
import numpy as np

np.random.seed(42)

arr = np.random.randint(1, 101, 15)

print(arr)

print("Mean:",np.mean(arr))

print("Median:",np.median(arr))

print("Std:",np.std(arr))

print("Min:",np.min(arr))

print("Max:",np.max(arr))

print("Descending:",np.sort(arr)[::-1])

print("Largest 3 indices:",np.argsort(arr) [-3:])

norm = (arr - arr.min()) / (arr.max() - arr.min())
print(norm)

[ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22]
Mean: 58.06666666666667
Median: 72.0
Std: 31.4843170836247
Min: 3
Max: 100
Descending: [100  93  88  87  83  75  75  72  61  52  24  22  21  15   3]
Largest 3 indices: [10  1 11]
[0.50515464 0.92783505 0.12371134 0.71134021 0.59793814 0.18556701
 0.82474227 0.86597938 0.74226804 0.74226804 0.87628866 1.
 0.21649485 0.         0.19587629]


 Section C - Pandas basics

In [81]:
# 7. Dataframe  operations

In [82]:
import pandas as pd

data = {
    'Name':['Aarav', 'Priya', 'Karan', 'Meera', 'Sahil'],
    'Age':[23, 21, 25, 22, 24],
    'Department':['AI', 'IT', 'Data science', 'AI', 'Web dev'],
    'Score':[88, 92, 79, 95, 67]
}

df = pd.DataFrame(data)

# a
print(df.head(3))
print(df.dtypes)

# b 
df['Grade'] = df['Score'].apply(
    lambda x: 'A' if x >= 90 else('B' if x >= 75 else 'C')
) 

# c
print(df.sort_values(by='Score',ascending=False))

# d
print(df[df['Department'] == 'AI'])

    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21            IT     92
2  Karan   25  Data science     79
Name          object
Age            int64
Department    object
Score          int64
dtype: object
    Name  Age    Department  Score Grade
3  Meera   22            AI     95     A
1  Priya   21            IT     92     A
0  Aarav   23            AI     88     B
2  Karan   25  Data science     79     B
4  Sahil   24       Web dev     67     C
    Name  Age Department  Score Grade
0  Aarav   23         AI     88     B
3  Meera   22         AI     95     A


In [83]:
# 8. Same dataframe operations

In [84]:
# a
print(df.groupby('Department')['Score'].mean())

# b
print(df.loc[df['Score'].idxmax()])

# c
df.rename(columns = {'Score':'Marks'},inplace=True)

# d
df.drop('Age', axis=1, inplace=True)
print(df)

Department
AI              91.5
Data science    79.0
IT              92.0
Web dev         67.0
Name: Score, dtype: float64
Name          Meera
Age              22
Department       AI
Score            95
Grade             A
Name: 3, dtype: object
    Name    Department  Marks Grade
0  Aarav            AI     88     B
1  Priya            IT     92     A
2  Karan  Data science     79     B
3  Meera            AI     95     A
4  Sahil       Web dev     67     C


In [85]:
# 9. Missing values handling

In [86]:
import pandas as pd
import numpy as np

data = {
    'Product':['Pen', 'Notebook', 'Eraser', 'Sharpener', 'Ruler'],
    'Price':[10, np.nan, 5, 8, np.nan],
    'Stock':[100, 50, np.nan, 30, 20]
}

df = pd.DataFrame(data)

# a
print(df.isnull().sum())

# b
df['Price'].fillna(df['Price'].mean(),inplace = True)

# c
df.dropna(subset=['Stock'],inplace=True)

# d
df.to_csv('Cleaned_products.csv',index=False)
print(df)

Product    0
Price      2
Stock      1
dtype: int64
     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0


C:\Users\Aarti  Gaikwad\AppData\Local\Temp\ipykernel_21360\182068681.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Price'].fillna(df['Price'].mean(),inplace = True)


In [90]:
# 10.Read CSV file

In [94]:
import pandas as pd

try:
    df = pd.read_csv("cleaned_products.csv")
    print("Shape:",df.shape)
    print("Columns:",df.columns)

    df['Total_value']=df['Price']*df['Stock']

    print(df)

    print(df.describe())

except FileNotFoundError:
    print("File not found")

Shape: (4, 3)
Columns: Index(['Product', 'Price', 'Stock'], dtype='object')
     Product      Price  Stock  Total_value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333
           Price       Stock  Total_value
count   4.000000    4.000000     4.000000
mean    8.333333   50.000000   444.166667
std     1.122167   35.590261   382.500303
min     7.666667   20.000000   153.333333
25%     7.666667   27.500000   218.333333
50%     7.833333   40.000000   311.666667
75%     8.500000   62.500000   537.500000
max    10.000000  100.000000  1000.000000
