Numpy

In [4]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [6]:
# Creating arrays

In [7]:
sample_array = np.array([1, 2, 3, 4])

In [8]:
sample_array

array([1, 2, 3, 4])

In [9]:
sample_array2 = np.array([19, 7, 8, 11, 6])

In [11]:
sample_array2

array([19,  7,  8, 11,  6])

In [12]:
# 2D Array(a matrix) with 2 rows and 2 columns

In [13]:
sample_array3 = np.array([[1, 2], [3, 4]])

In [14]:
sample_array3

array([[1, 2],
       [3, 4]])

In [15]:
sample_array4 = np.array([[19, 7], [11, 6]])

In [16]:
sample_array4

array([[19,  7],
       [11,  6]])

In [17]:
# 3D Tensor (2 matrices, each with 2 rows and 2 columns)

In [19]:
sample_tensor3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [20]:
sample_tensor3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [21]:
sample_tensor4 = np.array([[[19, 7], [11, 6]], [[8, 5], [4, 6]]])

In [22]:
sample_tensor4

array([[[19,  7],
        [11,  6]],

       [[ 8,  5],
        [ 4,  6]]])

In [23]:
# Dimension

In [24]:
# 0 - D Array(Scalar) 5
# 1 - D Array(Vector) [1, 2, 3, 4]
# 2 - D Array(Matrix)(rows and columns)
# 3 - D Array(Tensor) (page, rows and columns)

In [25]:
# Array properties

In [26]:
sample_array = np.array([[1, 2, 3], [4, 5, 6]])

In [27]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# Shape

In [29]:
sample_array.shape

(2, 3)

In [30]:
# Dimensions

In [31]:
sample_array.ndim

2

In [32]:
# Total elements 

In [33]:
sample_array.size

6

In [34]:
# Data type

In [35]:
sample_array.dtype

dtype('int64')

In [36]:
# 3 - D Array properties

In [37]:
sample_tensor3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [38]:
sample_tensor3 

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [39]:
# Shape

In [40]:
sample_tensor3.shape

(2, 2, 2)

In [41]:
# Dimensions

In [42]:
sample_tensor3.ndim 

3

In [43]:
# Total elements

In [44]:
sample_tensor3.size

8

In [45]:
# Data type

In [46]:
sample_tensor3.dtype

dtype('int64')

In [47]:
# Special array

In [48]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [53]:
np.arange(0, 30, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [54]:
np.arange(0, 100, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [57]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [58]:
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [59]:
# Indexing & Slicing

In [60]:
sample_array = np.array([10, 20, 30, 40])

In [61]:
sample_array

array([10, 20, 30, 40])

In [62]:
sample_array[0]

np.int64(10)

In [63]:
sample_array[2]

np.int64(30)

In [64]:
sample_array[-1]

np.int64(40)

In [65]:
# Slicing

In [66]:
sample_array[1:3]

array([20, 30])

In [67]:
# Array operations

In [68]:
a = np.array([1, 2, 3])

In [69]:
b = np.array([4, 5, 6])

In [70]:
a

array([1, 2, 3])

In [71]:
b

array([4, 5, 6])

In [72]:
a + b

array([5, 7, 9])

In [73]:
a - b

array([-3, -3, -3])

In [74]:
a * b

array([ 4, 10, 18])

In [75]:
a / b

array([0.25, 0.4 , 0.5 ])

In [76]:
a1 = np.array([19, 7, 8])

In [78]:
b1 = np.array([11, 6, 25])

In [79]:
a1

array([19,  7,  8])

In [80]:
b1

array([11,  6, 25])

In [81]:
a1 + b1

array([30, 13, 33])

In [83]:
a1 - b1

array([  8,   1, -17])

In [84]:
a1 * b1

array([209,  42, 200])

In [85]:
a1 / b1

array([1.72727273, 1.16666667, 0.32      ])

In [86]:
# Mathematical functions

In [87]:
sample_array = np.array([1, 4, 9])

In [88]:
sample_array

array([1, 4, 9])

In [89]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [94]:
sample_array1 = np.array([25, 49, 64])

In [95]:
sample_array1

array([25, 49, 64])

In [96]:
np.sqrt(sample_array1)

array([5., 7., 8.])

In [97]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [98]:
np.exp(sample_array1)

array([7.20048993e+10, 1.90734657e+21, 6.23514908e+27])

In [99]:
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [100]:
np.log(sample_array1)

array([3.21887582, 3.8918203 , 4.15888308])

In [101]:
# Statistical function

In [102]:
sample_array = np.array([1, 2, 3, 4, 5])

In [103]:
sample_array

array([1, 2, 3, 4, 5])

In [105]:
np.mean(sample_array)

np.float64(3.0)

In [107]:
np.median(sample_array)

np.float64(3.0)

In [110]:
np.std(sample_array)

np.float64(1.4142135623730951)

In [111]:
np.min(sample_array)

np.int64(1)

In [112]:
np.max(sample_array)

np.int64(5)

In [113]:
# Reshaping arrays

In [114]:
np.arange(0, 6, 1)

array([0, 1, 2, 3, 4, 5])

In [115]:
# Another way

In [117]:
sample_array = np.arange(6)

In [118]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [119]:
reshaped = sample_array.reshape(2, 3)

In [120]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [121]:
# Flattening

In [123]:
sample_array = np.array([[1, 2], [3,4]])

In [124]:
sample_array

array([[1, 2],
       [3, 4]])

In [125]:
sample_array.flatten()

array([1, 2, 3, 4])

In [126]:
sample_tensor3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [127]:
sample_tensor3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [128]:
sample_tensor3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [129]:
# Joining arrays

In [135]:
a1 = np.array([1, 2])

In [136]:
b1 = np.array([3, 4])

In [137]:
a1

array([1, 2])

In [138]:
b1

array([3, 4])

In [140]:
np.concatenate((a1, b1))

array([1, 2, 3, 4])

In [141]:
# Spliting arrays

In [142]:
sample_array = np.array([1, 2, 3, 4])

In [143]:
sample_array

array([1, 2, 3, 4])

In [149]:
np.array_split(sample_array,2)

[array([1, 2]), array([3, 4])]

In [150]:
# Random module

In [152]:
np.random.rand(3)

array([0.08724297, 0.08484676, 0.16401199])

In [153]:
np.random.randint(1, 10, 5)

array([5, 8, 4, 3, 5], dtype=int32)

In [154]:
# Axis concept

In [157]:
sample_array = np.array([[1, 2], [3, 4]])

In [158]:
sample_array

array([[1, 2],
       [3, 4]])

In [164]:
np.sum(sample_array, axis = 0) # Column->0

array([4, 6])

In [165]:
np.sum(sample_array, axis = 1) # Row->1

array([3, 7])

In [167]:
# Nan & missing values

In [168]:
sample_array = np.array([1, np.nan, 3])

In [169]:
sample_array

array([ 1., nan,  3.])

In [171]:
np.isnan(sample_array)

array([False,  True, False])

In [ ]:
# Create two numpy arrays and perform element wise addition subtraction multiplication and modulus operation

In [191]:
a2 = np.array([1, 2, 3, 4])

In [192]:
b2 = np.array([4, 5, 6, 7])

In [193]:
a1

array([1, 2])

In [194]:
b2

array([4, 5, 6, 7])

In [195]:
a2 + b2

array([ 5,  7,  9, 11])

In [196]:
a2 - b2

array([-3, -3, -3, -3])

In [197]:
a2 * b2

array([ 4, 10, 18, 28])

In [198]:
a2 / b2

array([0.25      , 0.4       , 0.5       , 0.57142857])